### ISSUE TITLE
Info not provided

### ISSUE THREAD

**Issue by Thisoneoverhere** [zendergo2/SheetsDB#16] opened 2017-05-19 18:52 UTC
When I try to use this, all I get is 'required information not provided'  Not only is that error not useful, the program does not function at all.  This was a total waste of my time.

**Comment by Thisoneoverhere** [comment] 2017-05-19 18:53
![info not provided](https://cloud.githubusercontent.com/assets/28813678/26262449/b84833c2-3c89-11e7-8e03-ce4b6f6c3eb1.png)

**Comment by zendergo2** [comment] 2017-05-19 19:05
I appreciate you filing an issue. With the info you gave me, I think this is intended behavior. The only thing you absolutely have to include at this point is the columns that you want to export. Like below. If that doesn't fix your problem, then there is a bug.

![image](https://cloud.githubusercontent.com/assets/6914035/26262765/7f8e1fd0-3c9b-11e7-81c3-06c98f1f2ae4.png)

Perhaps I should make the form more clear.

**Comment by Thisoneoverhere** [comment] 2017-05-19 19:08
I had included the columns, thank you for assuming I am an idiot.

**Comment by zendergo2** [comment] 2017-05-19 20:16
I apologize, and I don't think you're an idiot. I'm just a guy trying to figure out what's wrong with my app. Also, I was wrong before. Whether you include the columns or not shouldn't cause that specific error. My comment was unhelpful and I apologize for that.

I have been looking into it, but I do need more information to solve this issue.

- Which exporter are you using? JSON, HTML, XML, or CSV?
- For the sheet you wanted to export, was there:
  - a title in row 1 of every column you want to export
  - or, if it's just data, titles for every column in the form item labelled "Column titles in same order"

**Comment by Thisoneoverhere** [comment] 2017-05-19 21:55
HTML, just data, no titles

**Comment by zendergo2** [comment] 2017-05-19 22:18
Yeah, that's an issue with my app. I'm going to create a couple new ticket for this. What is happening essentially is that my exporter requires there to be titles for each column, and they can be entered through the form or automatically retrieved from the spreadsheet. With neither it just fails. I will get that fixed in the next milestone, which should be out in a week or so. 

Right now, if you want to export your data, the best way is to fill that "Column titles in same order" field with "col_1, col_2, col_3" etc (depending on how many columns you have). It will then create a header row with those columns. It isn't a great workaround, but you can save the settings so you only have to do it once per sheet. Then you can just delete everything inside the `<thead>` tag from the export.

I hope this works for you.

**Comment by zendergo2** [comment] 2018-01-28 03:49
Commit 48617c99b735379afc131f065770fa6ee6cd359a removes all required fields in the sidebar forms. Staged for next release.

**Closed as completed by zendergo2** 2018-01-28 03:49 UTC
